<?php

return [
    'fetch' => PDO::FETCH_OBJ,
    'default' => env('DB_CONNECTION', 'oracle1'),
    'connections' => [
        'oracle1' => [
            'driver' => 'oracle',
            //  'tns' => "(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 10.91.2.30)(PORT = 1521)) (CONNECT_DATA = (SERVICE_NAME = SIAKDB) (SID = SIAKDB)))",
            //'host' => env('DB_HOST', 'localhost'),
            'host' => '127.0.0.1',
//         'host' => '10.91.2.24',
            'port' => env('DB_PORT', '1521'),
            'database' => env('DB_DATABASE', 'SIAKDB'),
            'username' => env('DB_USERNAME', 'SIAKON'),
            'password' => env('DB_PASSWORD', 'ora_on_05'),
            'charset' => env('DB_CHARSET', 'AL32UTF8'),
            'prefix' => env('DB_PREFIX', ''),
            'prefix_schema' => env('DB_SCHEMA_PREFIX', ''),
        ], 
        'mysql' => [
            'driver' => 'mysql',
            'host' => 'localhost',
            'port' => '3306',
            'database' => 'db_any',  
            'username' => 'root',
            'password' => '',
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'oracle_siak' => [
            'driver' => 'oracle',
            'tns' => "(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521)) (CONNECT_DATA = (SERVICE_NAME = SIAKDB) (SID = SIAKDB)))",
            'host' => '127.0.0.1',
//            'host' => '127.0.0.1',
            'port' => '1521',
            'database' => 'SIAKDB',
            'username' => 'SIAKOFF',
            'password' => 'ora_off_05',
            'charset' => 'AL32UTF8',
            'prefix' => '',
            'prefix_schema' => '',
        ],
        'oracle1' => [
            'driver' => 'oracle',
            'tns' => "(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521)) (CONNECT_DATA = (SERVICE_NAME = SIAKDB) (SID = SIAKDB)))",
//            'host' => '127.0.0.1',  
            'host' => '127.0.0.1',
            'port' => '1521',
            'database' => 'SIAKDB',
            'username' => 'SIAKLYNN',
            'password' => 'siaklynn123',
            'charset' => 'AL32UTF8',
            'prefix' => '',
            'prefix_schema' => '',
        ],
        'oracle2' => [
            'driver' => 'oracle',
            'tns' => "(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 10.91.2.2)(PORT = 1522)) (CONNECT_DATA = (SERVICE_NAME = local) (SID = local)))",
            'host' => '10.91.2.2', //sesuaikan dengan alamat ip server perekaman
            'port' => '1522',
            'database' => 'LOCAL',
            'username' => 'BMUSER',
            'password' => 'BM123',
            'charset' => 'AL32UTF8',
            'prefix' => '',
            'prefix_schema' => '',
        ],
        'oracle3' => [
            'driver' => 'oracle',
            'tns' => "(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 10.91.2.2)(PORT = 1522)) (CONNECT_DATA = (SERVICE_NAME = ORCL) (SID = ORCL)))",
            'host' => '10.91.2.2',
            'port' => '1522',
            'database' => 'ORCL',
            'username' => 'BMUSER',
            'password' => 'technicalbsl7',
            'charset' => 'AL32UTF8',
            'prefix' => '',
            'prefix_schema' => '',
        ],
        'oracle5' => [
            'driver' => 'oracle',
            'tns' => "(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521)) (CONNECT_DATA = (SERVICE_NAME = SIAKDB) (SID = SIAKDB)))",
            'host' => '127.0.0.1',
            'port' => '1521',
            'database' => 'SIAKDB',
            'username' => 'SIAKLYNN',
            'password' => 'siaklynn123',
            'charset' => 'AL32UTF8',
            'prefix' => '',
            'prefix_schema' => '',
        ],
    ],
    'migrations' => 'migrations',
    'redis' => [
        'client' => 'predis',
        'default' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 0,
        ],
    ],
];
